### ISSUE TITLE
Additional human readable timestamp column for visual grouping

### ISSUE THREAD

**Issue by ylluminate** [SuprHackerSteve/Crescendo#10]
Having the `Timestamp` column is nice, but there are times when a more human readable localized timestamp would also be useful (ie, `2020-03-21 (20:41:34)`).  Could you please implement this column as well just beside the timestamp for more convenient referencing?  

The reason that this becomes helpful is that if we're looking at a large number of matched items it is associatively hard to see the time differential with the current format since one cannot readily discern what events occur minutes or hours apart without very close examination.

**Comment by SuprHackerSteve** [comment]
I have had more than a few requests for this, added to next release.

**Comment by ylluminate** [comment]
Have you built a new release yet?

**Comment by ylluminate** [comment]
Any update on this?  I've attempted to build the package myself, but getting some errors...

**Comment by SuprHackerSteve** [comment]
It has been merged. Please see the attached PR. I have no timeline on release right now.

**Comment by ylluminate** [comment]
I guess my problem here is that I'd like to go ahead and build this so I can use this to troubleshoot some critical issues I'm having that are difficult to track down without such a useful tool to analyze the logs / system events. I'm not having much luck in getting the current project to build.
