### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by big610** [SuprHackerSteve/Crescendo#15]
How to uninstall? Remove manually to Trash?
com.superhacker.crescendo.CrescendoExtension
com.superhacker.crescendo.CrescendoRxtension.systemextension
This operation can't be completed because you don't have permission to access some of the items?

**Comment by SuprHackerSteve** [comment]
Moving the app to the trash should delete the extension after reboot. This action is not meant to be managed by the user.

**Comment by big610** [comment]
These two:
com.superhacker.crescendo.CrescendoExtension
com.superhacker.crescendo.CrescendoRxtension.systemextesnion
You can't get them to the Trash, so rebooting useless. 
When attempting to move to Trash, reveal these messages.
"The operation can’t be completed because you don’t have permission to access some of the items."
You do not have permission to move the file or access it, couldn't be removed because you don't have permission to access it.
Are there any Terminal sudo commands?

**Comment by ideologysec** [comment]
My process was:

1. move the app to the Trash, delete it, reboot. Hung on logging out, force powered off.
2. `systemextensionsctl list` in Terminal showed just one (not 2) extensions remaining.
3. `sudo systemextensionsctl uninstall com.suprhackersteve.crescendo.CrescendoExtension` resulted in an error message.
4. rebooted again, hung at logging out, force powered off *again*, after restart, no extensions listed.

Based on the `systemextensionsctl` error message, you could probably disable SIP, use the `uninstall` argument for the TeamID, and then reboot to re-enable SIP as well.

<img width="1213" alt="Screen Shot 2020-05-12 at 14 04 00" src="https://user-images.githubusercontent.com/790061/81746503-75f2c280-945b-11ea-8360-5be9a8f40f8e.png">

**Comment by big610** [comment]
Thank you.

For others, who want to know how to Uninstall.

Disable SIP.
Find the two that wouldn't delete to Trash. Now with SIP disabled, they go straight to Trash, Empty.
Enable SIP.

No hanging, force quit at all. 
SIP= Restart... Command + R, to get into recovery. Utilities/Terminal.
Terminal only needed for SIP commands csrutil disable & csrutil enable.
