### ISSUE TITLE
Update to macOS Catalina

### ISSUE THREAD

**Issue by f-o-w-l** [SuprHackerSteve/Crescendo#16]
No events populating after updating to 10.15.4.

**Comment by slowcook** [comment]
Can you provide more details here? What have you done to troubleshoot?

**Comment by SuprHackerSteve** [comment]
@f-o-w-l can you provide some better detail to help assist? I have no reports of this and have suspicion it is a local issue. Please see the troubleshooting section for some steps.

**Comment by f-o-w-l** [comment]
Sorry, I sold my MacBook Air not long after reporting that issue and use a Linux laptop now 🤷‍♂️
