### ISSUE TITLE
Unload extension after use?

### ISSUE THREAD

**Issue by luckman212** [SuprHackerSteve/Crescendo#17]
Thanks for creating this! It's been incredibly useful for tracking down a few rogue processes on my Mac.

One question: is there any way to unload the Crescendo Extension after it's been activated? (short of a full system restart)

I tried a few `systemextensionsctl` commands but nothing worked.
```
$ systemextensionsctl list
1 extension(s)
--- com.apple.system_extension.endpoint_security
enabled	active	teamID	bundleID (version)	name	[state]
*	*	AD94776VX5	com.suprhackersteve.crescendo.CrescendoExtension (1.0.4/35)	Crescendo System Extension	[activated enabled]

$ systemextensionsctl reset
At this time, this tool cannot be used if System Integrity Protection is enabled.
This limitation will be removed in the near future.
Please remember to re-enable System Integrity Protection!

$ systemextensionsctl uninstall com.suprhackersteve.crescendo.CrescendoExtension
At this time, this tool cannot be used if System Integrity Protection is enabled.
This limitation will be removed in the near future.
Please remember to re-enable System Integrity Protection!
```

**Comment by SuprHackerSteve** [comment]
Hey @luckman212. You can unload the extension by using the menu bar item shown here:

<img width="243" alt="Screen Shot 2020-06-19 at 8 04 38 AM" src="https://user-images.githubusercontent.com/8420275/85130759-8721b280-b203-11ea-89af-3c5e2e1a49ef.png">

**Comment by luckman212** [comment]
Oh man. I dove straight for the commandline without even checking if there was a GUI option for this. Thanks again!
