### ISSUE TITLE
Homebrew formula wanted

### ISSUE THREAD

**Issue by hktonylee** [SuprHackerSteve/Crescendo#3]
As title this project will be even more awesome if it is available in Homebrew :)

**Comment by SuprHackerSteve** [comment]
@hktonylee good suggestion! Want to see if you can get something working? I am not familiar with how full apps work with homebrew (assume they would be using casks).

**Comment by x13a** [comment]
Let's try: [homebrew-cask](https://github.com/Homebrew/homebrew-cask/pull/104914)
