### ISSUE TITLE
No events shown

### ISSUE THREAD

**Issue by mehdideveloper** [SuprHackerSteve/Crescendo#4]
When I click on the start button, nothing happens except the circular progress bar that's spinning. No events are shown, even after waiting for half an hour.
I've moved the app to the Applications folder and also allowed the kernel extension. It doesn't have a CPU load either.

Running on 10.15.3

**Comment by SuprHackerSteve** [comment]
Please read the readme in full. Have you already enabled Full Disk Access?

**Comment by mehdideveloper** [comment]
Sorry. I had added the app to the Full Disk Access list.
It works now. Thanks
