### ISSUE TITLE
"Move to Applications folder" actually copies, not moves

### ISSUE THREAD

**Issue by steven-j-klein** [SuprHackerSteve/Crescendo#8]
If Crescendo is not in the Applications folder on first run, it throws up this dialog:
![image](https://user-images.githubusercontent.com/12419345/76422986-7f3cb180-637c-11ea-894e-3739ebf86f92.png)

I was running it from my downloads folder, so I clicked "Move to Applications Folder."

It did create a _copy_ in my Applications folder, but the original (in Downloads) remained.  I quit the app, thinking maybe it couldn't delete itself while it was running, but it still remained.

If this is the intended behavior, then the dialog box should be worded differently. Perhaps, "Copy to Applications Folder?"

If this is _not_ the intended behavior, then it's a bug that needs fixing.

**Comment by SuprHackerSteve** [comment]
@steven-j-klein I am using a third party library for this, please file with https://github.com/potionfactory/LetsMove
