### ISSUE TITLE
Whitelisting/blacklisting support

### ISSUE THREAD

**Issue by SuprHackerSteve** [SuprHackerSteve/Crescendo#9]
As a user, I'd like the ability to whitelist or blacklist process execution events on my mac using Crescendo.

**Comment by ideologysec** [comment]
Do you mean, prevent them from occurring a la Google's Santa?

**Comment by SuprHackerSteve** [comment]
@ideologysec I'm not familiar with the feature set of Google's Santa, but it will just block a process from launching.

**Comment by ideologysec** [comment]
Awesome.

Looks like Santa is in fact using a SysExt on 10.15+, possibly a decent starting point?

https://github.com/google/santa
